### ISSUE TITLE
Multiple issues - all the button LED stays on, reset button 

### ISSUE THREAD

**Issue by jps4you** [DIYTechBros/ButtonSmack#1]
Tested with multiple NANO boards and confirmed all wiring are exactly as shown in schematics. No issues programming the NANO boards. 
Symptom: all the button LEDs light up in pairs (p1 RED and p2 RED, p1 BLUE, p2 BLUE...etc) and once all of them are lit, they all stay lit. clicking the buttons does not do anything.
Rewired it to match hand drawing according to youtube video at 7:05 with extra 10K at the grounding leg. no change in the LED behavior.

Added reset button as shown in schematics
Symptom: when wired with 1K at the grounding side. reset button does not work. when 1k resister is remove and connect direct to ground, reset button works

some voltage readings...

V @ R1 = 820mV
V @ R2 = 904m
V @ R3 = 1.723V
V @ R4 = 2.566V
V @ R5 = 3.381V
V @ R6 = 4.19VmV
V @ R7 = 855mV
V @ R8 = 911V
V @ R9 = 1.698V
V @ R10 = 2.510V
V @ R11 = 3.303V
V @ R12 = 4.12V

V @ LEDs ~= 4.00V
V @ reset = 4.28V (open)
V @ VCC = 4.28V

**Comment by jps4you** [comment]
Rechecked the attached schematics and the A0 and A6 legs of the circuit is connected directly to ground, this prevents A0 and A6 from detecting any voltage. There should be another 10K ohms resister before the A0 and A6 legs going to ground. your YouTube video at 7:05 even shows it with the correct 10K ohm resister in the circuit. 

All the LEDs are still in the HIGH/ON state after the program initialized... this is the incorrect condition of the LEDs... continuing to debugging the circuit and the code... any input would be greatly appreciate it.

**Comment by DIYTechBros** [comment]
Thanks!
The diagram is updated in Commits on Sep 27, 2019.

Regarding the LEDs not switching off:
Are you using an original Arduino Nano?

There might be factors causing the button_values[] = {913, 429, 267, 179, 110};
to be offset if there are any difference in internal resistance. 

Can you leave you arduino connected to your computer and after line 85 (analog value=...)
add the line: 
Serial.println(String(analogValue));

That way you can confirm the analog values in the Serial Monitor.

It is a bit concerning that R1 and R7 is so fare apart.

**Comment by jps4you** [comment]
DIYTechBros, you guys ROCK!!! Thank you again for the foundation of this awesome classic game!!! 
Happy to report, the suggestion of reading the analog value using the serial monitor was key to solving the mystery of the misbehaving LEDs. I pull 1000 data points (i know way over kill) for each button read out, and took the average as the button_values, then expanded the bot_tol, and the game works like a charm!!

Many thanks again for the follow up and suggestions :D
