### ISSUE TITLE
winning score condition

### ISSUE THREAD

**Issue by jps4you** [DIYTechBros/ButtonSmack#2]
going through the code and found the condition of the following is incorrect. The corrected code to stop the game at 100 points list below.

Original code only stops the game once a play’s score is greater than 100
if(p1_score **<=** 100 and p2_score **<=** 100) {

Corrected code that will correctly stop the game once one of the player reaches score of 100
if(p1_score < 100 and p2_score < 100) {

**Comment by DIYTechBros** [comment]
Thanks! 
Updated in Commits on Sep 27, 2019
